language: python

jobs:
  include:
    - name: "Python Linux"
      python:
      - 3.8
      - 3.7
    - name: "Python on macOS"
      os: osx
      language: generic
      env:
        - OS_X_PYTHON_VERSION=python3.7
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      addons:
        homebrew:
          packages: python3
    - name: "Python on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - PYTHON="python"
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then PYTHON="python3" ; fi
  - echo "Using `$PYTHON --version`"
  - $PYTHON -m pip install --upgrade pip
  - $PYTHON -m pip install -r requirements.txt

script:
  - $PYTHON -m pylint --exit-zero features src
  - $PYTHON -m coverage run -m behave

